name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer uv
        run: pip install uv

      - name: Installer les dépendances
        run: uv pip install -e ".[dev]" --system

      - name: Lancer pytest
        run: pytest

